on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:

  buildNative:
    strategy:
      matrix:
        include:
          - os: macos-13
            scriptExt: "sh"
            libExt: "dylib"
            name: "x86_64"
          - os: macos-13-xlarge
            scriptExt: "sh"
            libExt: "dylib"
            name: "aarch64"
    name: Build Natives - ${{ matrix.name }}
    runs-on:  ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
            submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Install dependencies for macos-latest
        run: |
          brew install swig
          cd src/cpp/Effekseer/
          git submodule update --init --recommend-shallow --depth 1
      - name: Generate Swig Wrappers
        shell: bash
        run: |
          cd src
          chmod +x ./generate_swig_wrapper.${{ matrix.scriptExt }}
          ./generate_swig_wrapper.${{ matrix.scriptExt }}
          cd ..
      - name: Build natives for ${{ matrix.name }}
        shell: bash
        run: |  
          mkdir -p build/dist-native
          cd build
          cmake -D BUILD_DX12=OFF -D BUILD_EXAMPLES=OFF ..
          cmake --build . --config Release
          dest="dist-native/${{ matrix.name }}"
          mkdir -p "$dest"
          cp -v src/cpp/Release/libEffekseerNativeForJava.dylib "$dest"||cp -v src/cpp/libEffekseerNativeForJava.dylib "$dest"
      - name: Upload Natives
        uses: actions/upload-artifact@v4
        with:
          name: libEffekseerNativeForJava-${{ matrix.name }}.dylib
          path: build/dist-native/libEffekseerNativeForJava.dylib
